### ISSUE TITLE
Aram boost exploit question (how it works?) doesnt works for me

### ISSUE THREAD

**Issue by Sara-chikita** [BennyExtreme/KBotExt#7]
### Question

Why doesn't the aram boost exploit work? Should I have RP for it to work?

**Comment by BennyExtreme** [comment]
> Should I have RP for it to work?

Yes, next to the refund rp button you will find a question mark, putting your pointer over it will bring up instructions on how to use it.
Otherwise you can read the instructions directly from the code, [here](https://github.com/BennyExtreme/KBotExt/blob/16044f421adccd6d97fdcd3dd3e468d9d73c86e5/KBotExt/GameTab.h#L934).

You also have a button called "Is boost available for this account?" that checks for you whether your account is eligible for the exploit.

The way it works is simple, you need to have at least 95 RP in your account.
If you have at least 95 RP and there is a champ that you don't have (and you can buy it) the program buys it. (YOU WILL NOT HAVE TO USE THAT CHAMP).
You can later use boost for 24h and refund the champ to get your RP back. (Read the note next to the button to refund).
If the amount of RPs in your account minus the cost of a champ does not reach an amount less than 95 for the program you are not eligible for the exploit, you have too many RPs.
